---------------------------------------------------------------------
-------------------------Language Table------------------------------
---------------------------------------------------------------------
SDC.Lang = {
    AssistanceNeeded = "Assistance Needed!",
    AssistanceNeeded2 = "Assistance Needed At Marked Location!",
    PreformCheckup = "Preform Checkup",
    PreformCheckup2 = "Preforming Checkup",
    PutPedInStretcher = "Put In Stretcher",
    GrabStretcher = "Grab Stretcher",
    GrabStretcher2 = "Grab Civilian Out Of Ambulance",
    StoreStretcher = "Store Stretcher",
    StoreStretcher2 = "Put Civilian In Ambulance",
    MedicalEvaluation = "Medical Evaluation",
    Name = "Name",
    Age = "Age",
    Height = "Height",
    Measurement = "Inches",
    Status = "Status",
    Vitals = "Vitals",
    BP = "Blood Pressure",
    Heartrate = "Heartrate",
    Respiratory = "Respiratory Rate",
    BloodSugar = "Blood Sugar",
    Temperature = "Temperature",
    Injuries = "Injuries",
    Complaints = "Complaints",
    Observations = "Observations",
    Low = "Low",
    Normal = "Normal",
    High = "High",
    BPM = "(BPM)",
    MGDL = "(MG/DL)",
    Degrees = "(°F)",
    CouldntPickupPed = "Couldnt Pickup Civilian, Try Again!",
    CantPreformCheckup = "Cant Preform Checkup While Using Stretcher!",
    DropOffBlip = "Drop Off Civilian",
    DeliveredCivilian = "You delivered the Civilian! You were rewarded!",
    DropoffAtHospital = "Drop Off Civilian At",
    TransportNeeded = "Medical Transport",
    TransportNeeded2 = "Medical Transport Needed At Marked Location!",
    GrabTransportPatient = "Grab Transport Patient",
    DropTransportPatient = "Drop Off Transport Patient",
    GrabbingPatient = "Grabbing Transport Patient"
}